# NOTE: Current plan gives 1500 build minutes per month.
version: 2
jobs:
  test:
    docker:
      # Available from https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/thanos-io/thanos
    environment:
      GO111MODULE: 'on'
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
            version: 17.07.0-ce
      - run:
          name: Create Secret if PR is not forked
          # GCS integration tests are run only for author's PR that have write access, because these tests
          # require credentials. Env variables that sets up these tests will work only for these kind of PRs.
          command: |
            if ! [ -z ${GCP_PROJECT} ]; then
              echo $GOOGLE_APPLICATION_CREDENTIALS_CONTENT > $GOOGLE_APPLICATION_CREDENTIALS
              echo "Awesome! GCS integration tests are enabled."
            fi
      - run: make deps
      - run: make lint
      - run: make check-docs
      - run: make format
      - run:
          name: "Run all tests"
          # TODO(bplotka): Setup some S3 tests for CI.
          command: |
            if [ -z ${GCP_PROJECT} ]; then
              make test-local
              exit
            fi
            make test-only-gcs

  # Cross build is needed for publish_release but needs to be done outside of docker.
  cross_build:
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/thanos-io/thanos
    environment:
      GOBIN: "/home/circleci/.go_workspace/go/bin"
    steps:
    - checkout
    - run: make crossbuild
    - persist_to_workspace:
        root: .
        paths:
        - .build

  publish_master:
    docker:
      # Available from https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/thanos-io/thanos
    environment:
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run: ln -s .build/linux-amd64/thanos thanos
      - run: make docker
      - run: docker run thanos --help
      - run: echo "${QUAY_PASSWORD}" | docker login -u="${QUAY_USERNAME}" quay.io --password-stdin
      - run: make docker-push

  publish_release:
    docker:
      # Available from https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12.5
    working_directory: /go/src/github.com/thanos-io/thanos
    environment:
      GOBIN: "/go/bin"
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run: make tarballs-release
      - store_artifacts:
          path: .tarballs
          destination: releases
      - run: ln -s .build/linux-amd64/thanos thanos
      - run: make docker
      - run: docker run thanos --help
      - run: echo "${QUAY_PASSWORD}" | docker login -u="${QUAY_USERNAME}" quay.io --password-stdin
      - run: make docker-push DOCKER_IMAGE_TAG=$CIRCLE_TAG

workflows:
  version: 2
  thanos:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - publish_master:
        requires:
        - test
        filters:
          branches:
            only: master
    - cross_build:
        requires:
        - test
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
    - publish_release:
        requires:
        - test
        - cross_build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
